# Generated by Django 5.2.17 on 2026-10-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=255),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="city"),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("micro", "Micro (1–9)"),
                            ("small", "Small (10–49)"),
                            ("medium", "Medium (50–249)"),
                            ("large", "Large (250+)"),
                        ],
                        max_length=10,
                        verbose_name="size",
                    ),
                ),
                (
                    "websites",
                    models.TextField(
                        blank=True, help_text="One per line.", verbose_name="websites"
                    ),
                ),
                (
                    "phones",
                    models.TextField(
                        blank=True, help_text="One per line.", verbose_name="phones"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "questionnaire_note",
                    models.TextField(blank=True, verbose_name="questionnaire check"),
                ),
                (
                    "website_check_note",
                    models.TextField(blank=True, verbose_name="website check"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="name (English)"
                    ),
                ),
                (
                    "name_tr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="name (Turkish)"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True,
                        help_text="Used to match folder names and spreadsheets during import.",
                        max_length=200,
                        verbose_name="name (Russian)",
                    ),
                ),
                (
                    "iso_code",
                    models.CharField(
                        blank=True,
                        help_text="Two-letter code, e.g. TR, DE, KZ.",
                        max_length=2,
                        null=True,
                        unique=True,
                        verbose_name="ISO code",
                    ),
                ),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
                "ordering": ["name_en"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="full name"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="position"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("management", "Management"),
                            ("procurement", "Procurement"),
                            ("sales", "Sales"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                        verbose_name="category",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=60, verbose_name="phone"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="directory.company",
                        verbose_name="company",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact person",
                "verbose_name_plural": "contact persons",
                "ordering": ["company", "category", "full_name"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="directory.country",
                verbose_name="country",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="start date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="city"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="directory.country",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="name (English)"
                    ),
                ),
                (
                    "name_tr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="name (Turkish)"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True,
                        help_text="Used to match folder names and spreadsheets during import.",
                        max_length=200,
                        verbose_name="name (Russian)",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="directory.industry",
                        verbose_name="parent industry",
                    ),
                ),
            ],
            options={
                "verbose_name": "industry",
                "verbose_name_plural": "industries",
                "ordering": ["name_en"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="company",
            name="industries",
            field=models.ManyToManyField(
                blank=True,
                related_name="companies",
                to="directory.industry",
                verbose_name="industries",
            ),
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scheduled at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("held", "Held"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("outcome", models.TextField(blank=True, verbose_name="outcome")),
                (
                    "company_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings_as_a",
                        to="directory.company",
                        verbose_name="first company",
                    ),
                ),
                (
                    "company_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings_as_b",
                        to="directory.company",
                        verbose_name="second company",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="directory.event",
                        verbose_name="event",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting",
                "verbose_name_plural": "meetings",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="companies",
                to="directory.tag",
                verbose_name="tags",
            ),
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("list", "Company list"),
                            ("website", "Company website"),
                            ("ctb_mail", "CTB mailbox"),
                            ("manual", "Entered manually"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="source",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(blank=True, max_length=200, verbose_name="person"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="department / role"
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        help_text="Grouping for e-mails that are not linked to a company.",
                        max_length=255,
                        verbose_name="group",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "correspondence",
                    models.TextField(blank=True, verbose_name="CTB correspondence"),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="e-mails sent"
                    ),
                ),
                (
                    "last_sent_on",
                    models.DateField(blank=True, null=True, verbose_name="last sent"),
                ),
                ("replied", models.BooleanField(default=False, verbose_name="replied")),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="The link to the company was guessed and should be checked.",
                        verbose_name="needs review",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty if the company is not known yet.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="directory.company",
                        verbose_name="company",
                    ),
                ),
            ],
            options={
                "verbose_name": "e-mail address",
                "verbose_name_plural": "e-mail addresses",
                "ordering": ["company", "source", "email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "email"), name="unique_company_email"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("buyer", "Buyer"),
                            ("seller", "Seller"),
                            ("both", "Buyer and seller"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "interests",
                    models.TextField(
                        blank=True,
                        help_text="What the company is looking for or offering at this event.",
                        verbose_name="interests",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="directory.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="directory.event",
                        verbose_name="event",
                    ),
                ),
            ],
            options={
                "verbose_name": "participation",
                "verbose_name_plural": "participations",
                "ordering": ["event", "company"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "company"), name="unique_event_company"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="directory_c_name_679348_idx"),
        ),
    ]
