# Generated by Django 5.2.17 on 2026-10-06 14:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="break_end",
            field=models.TimeField(
                blank=True,
                default=datetime.time(14, 0),
                null=True,
                verbose_name="break until",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="break_start",
            field=models.TimeField(
                blank=True,
                default=datetime.time(13, 0),
                null=True,
                verbose_name="break from",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="day_end",
            field=models.TimeField(
                default=datetime.time(17, 0), verbose_name="meetings end at"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="day_start",
            field=models.TimeField(
                default=datetime.time(10, 0), verbose_name="meetings start at"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(240),
                ],
                verbose_name="meeting length (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tables",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Meetings held at the same time. Leave empty for no limit.",
                null=True,
                verbose_name="number of tables",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="table",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="table"
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="max_meetings",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Empty: no limit.",
                null=True,
                verbose_name="max. meetings",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                    ("attended", "Attended"),
                ],
                default="confirmed",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="wanted_countries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Empty: any country.",
                related_name="+",
                to="directory.country",
                verbose_name="wants to meet countries",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="wanted_industries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Empty: companies of the same industries.",
                related_name="+",
                to="directory.industry",
                verbose_name="wants to meet industries",
            ),
        ),
    ]
