# Generated by Django 5.2.17 on 2026-10-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_invitations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participation",
            options={
                "ordering": ["event", "company"],
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
            },
        ),
    ]
