# Generated by Django 5.2.17 on 2026-10-06 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_invitation_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("subject", models.CharField(max_length=300, verbose_name="subject")),
                ("body", models.TextField(verbose_name="text")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
            ],
            options={
                "verbose_name": "invitation template",
                "verbose_name_plural": "invitation templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        default="smtp.gmail.com",
                        max_length=200,
                        verbose_name="SMTP server",
                    ),
                ),
                ("port", models.PositiveIntegerField(default=587, verbose_name="port")),
                ("use_tls", models.BooleanField(default=True, verbose_name="use TLS")),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Usually the full e-mail address.",
                        max_length=200,
                        verbose_name="login",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="For Gmail use an app password (Google account → Security → App passwords).",
                        max_length=200,
                        verbose_name="password",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="sender address"
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        blank=True,
                        default="CTB",
                        max_length=200,
                        verbose_name="sender name",
                    ),
                ),
            ],
            options={
                "verbose_name": "mail settings",
                "verbose_name_plural": "mail settings",
            },
        ),
        migrations.CreateModel(
            name="TemplateAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="attachments/%Y/%m/", verbose_name="file"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="directory.emailtemplate",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature",
                    models.TextField(
                        blank=True,
                        help_text="Added at the end of every e-mail you send from the site.",
                        verbose_name="signature",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
            },
        ),
    ]
