# Generated by Django 5.2.17 on 2026-10-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0006_email_templates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("export_data", "Can export companies and e-mails to Excel")
                ],
                "verbose_name": "company",
                "verbose_name_plural": "companies",
            },
        ),
    ]
