# Generated by Django 5.2.17 on 2026-10-06 20:26

import directory.models
import django.db.models.deletion
from django.db import migrations, models


def fill_tokens(apps, schema_editor):
    # Each existing event and invitation needs its own random link token.
    for model, field, make in [("Event", "registration_key", directory.models.new_event_key),
                               ("Participation", "registration_token",
                                directory.models.new_registration_token)]:
        Model = apps.get_model("directory", model)
        for obj in Model.objects.filter(**{f"{field}__isnull": True}).only("pk"):
            Model.objects.filter(pk=obj.pk).update(**{field: make()})


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0007_export_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="check_note",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="check result"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="check_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("valid", "OK"),
                    ("suspicious", "Possible typo"),
                    ("invalid", "Invalid"),
                ],
                help_text="Result of the address check. Empty: not checked.",
                max_length=10,
                verbose_name="check",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="checked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="checked"),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_key",
            field=models.CharField(
                editable=False, max_length=32, null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_open",
            field=models.BooleanField(
                default=True,
                help_text="Companies can register through the form link.",
                verbose_name="registration form open",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="registered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the company filled in the registration form.",
                null=True,
                verbose_name="registered",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="registration_token",
            field=models.CharField(
                editable=False, max_length=32, null=True,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("email", "E-mail sent"),
                    ("call", "Call"),
                    ("reply", "Reply received"),
                    ("note", "Note"),
                    ("registration", "Registration form"),
                ],
                max_length=12,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="source",
            field=models.CharField(
                choices=[
                    ("list", "Company list"),
                    ("website", "Company website"),
                    ("ctb_mail", "CTB mailbox"),
                    ("manual", "Entered manually"),
                    ("registration", "Registration form"),
                ],
                default="manual",
                max_length=12,
                verbose_name="source",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("shortlisted", "To invite"),
                    ("invited", "Invited"),
                    ("registered", "Registered"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                    ("attended", "Attended"),
                ],
                default="confirmed",
                max_length=12,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="Attendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="full name"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="position"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=60, verbose_name="phone"),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="directory.participation",
                        verbose_name="invitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "participant",
                "verbose_name_plural": "participants",
                "ordering": ["participation", "pk"],
            },
        ),
        migrations.RunPython(fill_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="event",
            name="registration_key",
            field=models.CharField(default=directory.models.new_event_key, editable=False,
                                   max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="participation",
            name="registration_token",
            field=models.CharField(default=directory.models.new_registration_token,
                                   editable=False, max_length=32, unique=True),
        ),
    ]
