# Generated by Django 5.2.17 on 2026-10-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0008_email_check_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="industries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sectors of the event. A registering company without a sector gets these.",
                related_name="events",
                to="directory.industry",
                verbose_name="sectors",
            ),
        ),
    ]
